### ISSUE TITLE
Uncaught Error: listen EADDRINUSE :::3000

### ISSUE THREAD

**Issue by vipbox** [blazeu/atom-browsersync#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [atom-browsersync](https://github.com/blazeu/atom-browsersync) package 0.2.0

### Stack Trace

Uncaught Error: listen EADDRINUSE :::3000

```
At events.js:160

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at module.exports.plugin (/packages/atom-browsersync/node_modules/browser-sync/dist/server/index.js:27:25)
    at /packages/atom-browsersync/node_modules/browser-sync/dist/async.js:177:52)
    at /packages/atom-browsersync/node_modules/browser-sync/dist/browser-sync.js:120:14
    at iterate (/packages/atom-browsersync/node_modules/browser-sync/dist/utils.js:253:13)
    at /packages/atom-browsersync/node_modules/browser-sync/dist/utils.js:264:25
    at executeTask (/packages/atom-browsersync/node_modules/browser-sync/dist/browser-sync.js:136:13)
    at /packages/atom-browsersync/node_modules/browser-sync/dist/async.js:166:9)
    at /packages/atom-browsersync/node_modules/browser-sync/dist/browser-sync.js:120:14
    at iterate (/packages/atom-browsersync/node_modules/browser-sync/dist/utils.js:253:13)
    at /packages/atom-browsersync/node_modules/browser-sync/dist/utils.js:264:25
    at executeTask (/packages/atom-browsersync/node_modules/browser-sync/dist/browser-sync.js:136:13)
    at /packages/atom-browsersync/node_modules/browser-sync/dist/async.js:155:9)
    at /packages/atom-browsersync/node_modules/browser-sync/dist/browser-sync.js:120:14
    at iterate (/packages/atom-browsersync/node_modules/browser-sync/dist/utils.js:253:13)
    at /packages/atom-browsersync/node_modules/browser-sync/dist/utils.js:264:25
    at executeTask (/packages/atom-browsersync/node_modules/browser-sync/dist/browser-sync.js:136:13)
    at /packages/atom-browsersync/node_modules/browser-sync/dist/async.js:148:9)
    at /packages/atom-browsersync/node_modules/browser-sync/dist/browser-sync.js:120:14
    at iterate (/packages/atom-browsersync/node_modules/browser-sync/dist/utils.js:253:13)
    at /packages/atom-browsersync/node_modules/browser-sync/dist/utils.js:264:25
    at executeTask (/packages/atom-browsersync/node_modules/browser-sync/dist/browser-sync.js:136:13)
    at /packages/atom-browsersync/node_modules/browser-sync/dist/async.js:133:9)
    at /packages/atom-browsersync/node_modules/browser-sync/dist/browser-sync.js:120:14
    at iterate (/packages/atom-browsersync/node_modules/browser-sync/dist/utils.js:253:13)
    at /packages/atom-browsersync/node_modules/browser-sync/dist/utils.js:264:25
```

### Commands

```
  2x -0:46 atom-browsersync:open-in-browser (input.hidden-input)
```

### Non-Core Packages

```
atom-browsersync 0.2.0 
atom-html-preview 0.2.5 
browser-plus 0.0.98 
browser-plus-open-new-window 0.0.1 
pinegrow-atom 0.3.1 
```

**Comment by blazeu** [comment]
Port 3000 is being used by another application in your device.

You can change the port to something else in the config.

**Comment by vipbox** [comment]
obrigado!

2018-01-30 21:59 GMT-02:00 Surya Widi <notifications@github.com>:
